### PR TITLE
feat: add support for required lang param

### PR DESCRIPTION
**Pull request by Epoxide**
Currently only `[[lang]]` as an optional param is permitted. This PR makes it possible to use `[lang]` as a required param as well.

Example:

Routes:

`/[lang]`
`/[lang]/about`

Config:

```ts
return await sitemap.response({
  origin: 'https://www.example.com',
  page: params.page,
  lang: {
    default: 'en',
    alternates: ['sv', 'nb', 'da'],
  },
})
```

Output:

```xml
<url>
<loc>https://www.example.com/en</loc>
<xhtml:link rel="alternate" hreflang="en" href="https://www.example.com/en"/>
<xhtml:link rel="alternate" hreflang="sv" href="https://www.example.com/sv"/>
<xhtml:link rel="alternate" hreflang="nb" href="https://www.example.com/nb"/>
<xhtml:link rel="alternate" hreflang="da" href="https://www.example.com/da"/>
</url>
<url>
<loc>https://www.example.com/sv</loc>
<xhtml:link rel="alternate" hreflang="en" href="https://www.example.com/en"/>
<xhtml:link rel="alternate" hreflang="sv" href="https://www.example.com/sv"/>
<xhtml:link rel="alternate" hreflang="nb" href="https://www.example.com/nb"/>
<xhtml:link rel="alternate" hreflang="da" href="https://www.example.com/da"/>
</url>
<url>
<loc>https://www.example.com/nb</loc>
<xhtml:link rel="alternate" hreflang="en" href="https://www.example.com/en"/>
<xhtml:link rel="alternate" hreflang="sv" href="https://www.example.com/sv"/>
<xhtml:link rel="alternate" hreflang="nb" href="https://www.example.com/nb"/>
<xhtml:link rel="alternate" hreflang="da" href="https://www.example.com/da"/>
</url>
<url>
<loc>https://www.example.com/da</loc>
<xhtml:link rel="alternate" hreflang="en" href="https://www.example.com/en"/>
<xhtml:link rel="alternate" hreflang="sv" href="https://www.example.com/sv"/>
<xhtml:link rel="alternate" hreflang="nb" href="https://www.example.com/nb"/>
<xhtml:link rel="alternate" hreflang="da" href="https://www.example.com/da"/>
</url>
<url>
<loc>https://www.example.com/en/about</loc>
<xhtml:link rel="alternate" hreflang="en" href="https://www.example.com/en/about"/>
<xhtml:link rel="alternate" hreflang="sv" href="https://www.example.com/sv/about"/>
<xhtml:link rel="alternate" hreflang="nb" href="https://www.example.com/nb/about"/>
<xhtml:link rel="alternate" hreflang="da" href="https://www.example.com/da/about"/>
</url>
<url>
<loc>https://www.example.com/sv/about</loc>
<xhtml:link rel="alternate" hreflang="en" href="https://www.example.com/en/about"/>
<xhtml:link rel="alternate" hreflang="sv" href="https://www.example.com/sv/about"/>
<xhtml:link rel="alternate" hreflang="nb" href="https://www.example.com/nb/about"/>
<xhtml:link rel="alternate" hreflang="da" href="https://www.example.com/da/about"/>
</url>
<url>
<loc>https://www.example.com/nb/about</loc>
<xhtml:link rel="alternate" hreflang="en" href="https://www.example.com/en/about"/>
<xhtml:link rel="alternate" hreflang="sv" href="https://www.example.com/sv/about"/>
<xhtml:link rel="alternate" hreflang="nb" href="https://www.example.com/nb/about"/>
<xhtml:link rel="alternate" hreflang="da" href="https://www.example.com/da/about"/>
</url>
<url>
<loc>https://www.example.com/da/about</loc>
<xhtml:link rel="alternate" hreflang="en" href="https://www.example.com/en/about"/>
<xhtml:link rel="alternate" hreflang="sv" href="https://www.example.com/sv/about"/>
<xhtml:link rel="alternate" hreflang="nb" href="https://www.example.com/nb/about"/>
<xhtml:link rel="alternate" hreflang="da" href="https://www.example.com/da/about"/>
</url>
```

### CODE REVIEW

**Comment by jasongitmail** [comment]
Awesome. Thanks!

The related test cases should be updated too before merging. If you'd be up to push commits for that, that'd be great (and faster to merge) or I can take a look at it too.

**Comment by Epoxide** [comment]
> Awesome. Thanks!
> 
> The related test cases should be updated too before merging. If you'd be up to push commits for that, that'd be great (and faster to merge) or I can take a look at it too.

I can take a look first 👍

**Comment by Epoxide** [comment]
Actually I'm not quite sure how to do the routes with both `[[lang]]` and `[lang]` at the root level without a conflict. Any ideas?

Also I skipped editing the docs in the README as I'm not sure about any other i18n library as I'm not running any third party lib. If you could take a look at that too would be great.

**Comment by jasongitmail** [comment]
Appreciate you opening this. Closing now that we're focusing on the PR that supports lang params now too. Feel free to jump in on that thread to collaborate on the review. Thanks!

**Pull request closed without merging**
